// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5509.Delta;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainbackLeftMotor;
    public static WPI_TalonSRX driveTrainfrontLeftMotor;
    public static WPI_TalonSRX driveTrainfrontRightMotor;
    public static WPI_TalonSRX driveTrainbackRightMotor;
    public static MecanumDrive driveTrainmecanumDrive;
    public static AnalogGyro driveTrainDONOTUSE;
    public static WPI_TalonSRX liftDriveliftMotor;
    public static WPI_TalonSRX intakeDriveintakeMotor1;
    public static WPI_TalonSRX intakeDriveintakeMotor2;
    public static WPI_TalonSRX endGameDriveendGameMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    
    public static ADXRS450_Gyro gyro;
    

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainbackLeftMotor = new WPI_TalonSRX(3);
        
        
        driveTrainfrontLeftMotor = new WPI_TalonSRX(1);
        
        
        driveTrainfrontRightMotor = new WPI_TalonSRX(2);
        
        
        driveTrainbackRightMotor = new WPI_TalonSRX(4);
        
        
        driveTrainmecanumDrive = new MecanumDrive(driveTrainfrontLeftMotor, driveTrainbackLeftMotor,
              driveTrainfrontRightMotor, driveTrainbackRightMotor);
        LiveWindow.addActuator("DriveTrain", "mecanumDrive", driveTrainmecanumDrive);
        driveTrainmecanumDrive.setSafetyEnabled(true);
        driveTrainmecanumDrive.setExpiration(0.1);
        driveTrainmecanumDrive.setMaxOutput(1.0);

        driveTrainDONOTUSE = new AnalogGyro(0);
        LiveWindow.addSensor("DriveTrain", "DONOTUSE", driveTrainDONOTUSE);
        driveTrainDONOTUSE.setSensitivity(0.007);
        liftDriveliftMotor = new WPI_TalonSRX(5);
        
        
        intakeDriveintakeMotor1 = new WPI_TalonSRX(6);
        
        
        intakeDriveintakeMotor2 = new WPI_TalonSRX(7);
        
        
        endGameDriveendGameMotor = new WPI_TalonSRX(8);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        //driveTrainbackLeftMotor.setInverted(true);
        //driveTrainbackRightMotor.setInverted(true);
        //driveTrainfrontRightMotor.setInverted(true);
        gyro = new ADXRS450_Gyro();
        LiveWindow.addSensor("DriveTrain", "gyro", gyro);
    }
}
