// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5509.Delta.subsystems;

import org.usfirst.frc5509.Delta.RobotMap;
import org.usfirst.frc5509.Delta.commands.UpDown;

import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class LiftDrive extends Subsystem {
	
	
	public static final String AUTONOMOUS_LIFT_SPEED_KEY = "Autonomous Lift Speed" ;
	public static final Double AUTONOMOUS_LIFT_SPEED_DEFAULT = 1.0 ; 
	
	public static final String AUTONOMOUS_LIFT_SECONDSPERINCHES_KEY = "Autonomous Lift Seconds Per inches" ;
	public static final Double AUTONOMOUS_LIFT_SECONDSPERINCHES_DEFAULT =  .11; 
	//test by timing the time it takes to go bottom to top

	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX liftMotor = RobotMap.liftDriveliftMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


	@Override
	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new UpDown());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	@Override
	public void periodic() {
		// Put code here to be run every loop

	}

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void run(double value) {
		liftMotor.set(value);
	}

	public void stop() {
		run(0);
	}

}
